### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by ComFreek** [IonicaBizau/code-style#1]
Thanks for making this, I'll use it the next time I issue a PR.

Two comments:
- One shouldn't delete properties. This slows down the execution time.
- `for .. in` loops should have a `isOwnProperty` check. The other solution is to use [`Object.keys()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys):
  
  ``` javascript
  var obj = getObjectFromSomewhere();
  object.keys(obj).forEach(function (key) {
  console.log(key + " => " + obj[key]);
  });
  ```
  
  (Object.keys() being an ES 5 method is only supported by up-to-date browsers, but I think you can neglect IE 6 users with regard to your projects.)

**Comment by IonicaBizau** [comment]
> `for .. in` loops should have a `isOwnProperty` check

From what I know, this is just for IE, right?

**Comment by ComFreek** [comment]
No, for all browsers. `for .. in` does not only loop through the current object's properties, but also through the prototype chain (as opposed to `Object.keys()`).

**Comment by IonicaBizau** [comment]
Cannot reproduce it on Chromium:

``` js
> obj = { a: 1 }
> for (var k in obj) console.log(k)

a
```

**Comment by ComFreek** [comment]
@IonicaBizau Consider this example: http://jsfiddle.net/801rd9kt/

**Comment by ComFreek** [comment]
Your example **does loop** through the prototype chain, which happens to be empty:

Run this to see that:

```
Object.getPrototypeOf({a: 1})
```

**Comment by IonicaBizau** [comment]
I haven't switched on `Object.keys(obj).forEach(...)` yet, but I started using it in the latest projects. Thanks for the suggestion.

**Comment by ComFreek** [comment]
:+1:  BTW, I came across the `for...of` loop (new in ES 6 - Harmony): https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/for...of It is even more beautiful than forEach.

**Comment by IonicaBizau** [comment]
Nice, but until ES6 will be supported officially, I use `forEach`...
